Delete legacy decryption code
hyperledger/aries-framework-rs pull request #134
Opened 2020-10-11 09:48 UTC by Patrik-Stas

Signed-off-by: Patrik Stas <patrik.stas@absa.africa>

2020-10-19 12:07 UTC, mirgee requested changes

2020-10-19 12:07 UTC, mirgee commented on libvcx/src/aries/handlers/connection/agent_info.rs
> +    fn decode_message_noauth(&self, message: &Message) -> VcxResult<A2AMessage> {
Maybe `decrypt_decode_message_noauth` is more accurate

2020-10-19 13:58 UTC, Patrik-Stas commented on libvcx/src/api/utils.rs
> +authenticated and a message appearing to be received from certain connection might been spoofed.")]
Okay

2020-10-19 14:14 UTC, Patrik-Stas commented on libvcx/src/aries/mod.rs
> +    #[cfg(feature = "to_restore")] // todo: this is the problem alice.download_message("credential-offer");
good catch, restored

2020-10-19 19:31 UTC, Patrik-Stas commented on libvcx/src/aries/utils/encryption_envelope.rs
> +        assert_eq!(ack, EncryptionEnvelope::anon_unpack(message_2).unwrap());
tests added

2020-10-19 19:32 UTC, Patrik-Stas commented
@mirgee great points, addressed, ready for re-review

2020-10-20 07:12 UTC, mirgee approved these changes

2020-10-20 07:12 UTC, merged