WIP: Expose get requested attributes for holder
hyperledger/aries-framework-rs pull request #141
Opened 2020-10-15 18:55 UTC by mirgee

Signed-off-by: Miroslav Kovar <miroslavkovar@protonmail.com>

2020-10-17 13:22 UTC, Patrik-Stas commented on libvcx/src/aries/handlers/issuance/holder/states/finished.rs
> +        let mut new_map: HashMap<String, String> = HashMap::new();
Thought this snippet bellow could look bit different. Came up with this:
```
        let mut new_map = serde_json::map::Map::new();
        match cred_data.values.as_object() {
            Some(values) => {
                for (key, value) in values {
                    let val = value["raw"]
                        .as_str()
                        .ok_or(VcxError::from_msg(VcxErrorKind::InvalidJson, "Missing raw encoding on credential value"))?
                        .into();
                    new_map.insert(key.clone(), val);
                };
                Ok(Value::Object(new_map).to_string())
            }
            _ => Err(VcxError::from_msg(VcxErrorKind::InvalidJson, format!("Cannot convert {:?} into object", content)))
        }
```

2020-10-17 13:32 UTC, Patrik-Stas commented on libvcx/src/aries/handlers/issuance/holder/states/offer_received.rs
> +        let mut new_map: HashMap<String, String> = HashMap::new();
You can use `let mut new_map = serde_json::map::Map::new();` and then return `Ok(Value::Object(new_map).to_string())` online `49` - so there wouldn't be any chance of serialization error on rust typing level. 
(The `insert` method on `serde_json::map::Map` accepts as value only `Value`, which is known to be serializable.)

2020-10-17 13:33 UTC, Patrik-Stas commented on libvcx/src/aries/handlers/issuance/holder/state_machine.rs
> +            _ => Err(VcxError::from_msg(VcxErrorKind::NotReady, "Cannot get credential attributes: credential offer must be receieved first"))
`...credential offer or credential ...`

2020-10-17 13:39 UTC, Patrik-Stas commented on libvcx/src/aries/messages/issuance/credential.rs
> +impl TryFrom<A2AMessage> for Credential {
Is this used somewhere?

2020-10-17 13:41 UTC, Patrik-Stas commented
Can you also extend Java and iOS wrapper? Probably any mobile app would want to use this.

2020-10-17 13:41 UTC, Patrik-Stas requested changes
Can you also extend Java and iOS wrapper? Probably any mobile app would want to use this.

2020-10-17 16:03 UTC, mirgee commented on libvcx/src/aries/handlers/issuance/holder/state_machine.rs
> +            _ => Err(VcxError::from_msg(VcxErrorKind::NotReady, "Cannot get credential attributes: credential offer must be receieved first"))
The second implies the first :)

2020-10-19 15:08 UTC, Patrik-Stas requested changes
please rename added function for proof to getProofRequestAttachment as we agreed

2020-10-21 07:13 UTC, Patrik-Stas approved these changes

2020-10-21 07:17 UTC, merged